### ISSUE TITLE
Check if mailguninstance is alive

### ISSUE THREAD

**Issue by JAertgeerts** [LobeTia/trailpack-mailgun#18]
Have a worker running, restarted it and got the task before the mailgun trailpack was initialized & validated. Called the messagesSend method and got an error saying that I can't call messages() of undefined.
Worth adding a check in to see if mailguninstance is alive or do I have to fix that on the tasker?

**Comment by LobeTia** [comment]
Maybe I can emit an event when the instance is ready so you can start your queue worker when the deps are ok.
Somethings like `this.app.on('trailpack-mailgun:ready', startWorker)`

**Comment by JAertgeerts** [comment]
I'm now letting the tasker wait for trails to be ready before initialising it. Mailgun instance seems to take some time to get ready.

**Comment by LobeTia** [comment]
Mailgun is instanced without waiting for trails:ready
I also added an event which you can listen to `trailpack-mailgun:ready` for knowing when the instance is ready
